name: google_maps_flutter_custom_info_window
description: Single-entry wrapper package for Google Maps Flutter with configurable native custom info window support.
version: 0.3.0
homepage: https://github.com/Averoes12/custom-info-window-maps
repository: https://github.com/Averoes12/custom-info-window-maps

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter:
    git:
      url: git@github.com:Averoes12/custom-info-window-maps.git
      ref: v0.2.3
      path: google_maps_flutter
  google_maps_flutter_android:
    git:
      url: git@github.com:Averoes12/custom-info-window-maps.git
      ref: v0.2.3
      path: google_maps_flutter_android
  google_maps_flutter_ios:
    git:
      url: git@github.com:Averoes12/custom-info-window-maps.git
      ref: v0.2.3
      path: google_maps_flutter_ios
  google_maps_flutter_platform_interface:
    git:
      url: git@github.com:Averoes12/custom-info-window-maps.git
      ref: v0.2.3
      path: google_maps_flutter_platform_interface

flutter:
